aws_region         = "ap-south-1"
project_name       = "taskboard"
vpc_cidr           = "10.30.0.0/16"
public_subnet_cidr = "10.30.1.0/24"
instance_type      = "t3.small"
ssh_allowed_cidr   = "0.0.0.0/0"
bucket_name        = "gaurav-taskboard-artifacts"
