apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskboard.fullname" . }}
  labels: {{- include "taskboard.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels: {{- include "taskboard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "taskboard.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.config.PORT | quote }}
        prometheus.io/path: /metrics
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: taskboard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.PORT }}
          envFrom:
            - configMapRef:
                name: {{ include "taskboard.fullname" . }}-config
          env:
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "taskboard.fullname" . }}-secret
                  key: ADMIN_TOKEN
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.config.DATA_DIR }}
          {{- end }}
          startupProbe:
            httpGet: { path: /health, port: http }
            periodSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet: { path: /ready, port: http }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: http }
            periodSeconds: 10
            failureThreshold: 3
          resources: {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "taskboard.fullname" . }}-data
      {{- end }}
